language: ruby
rvm:
    - 2.2.5
    - 2.2.2

script: ./script/cibuild

branches:
  only:
      - src

env:
    global:
      - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false
