# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Raymond Colebaugh
subtitle: Development, Operations, and Security
email: raymondcolebaugh@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    I am a recent CS graduate with interests in security, automation, IDS, crypto,
    HA, and distributed systems.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://raymondcolebaugh.github.io" # the base hostname & protocol for your site
twitter_username: rcolebaugh
github_username:  raymondcolebaugh
bitbucket_username:  raymondcolebaugh
linkedin_username: raymondcolebaugh
bitcoin_address: 1Dn2JSjGt1XGPQRq698JqHzzV1cSEK8HYf

# Build settings
markdown: kramdown
collections:
    projects:
        output: true
gems:
    - jekyll-assets
assets:
    assets:
    - "*.js"
    - "*.png"
    - "*.jpg"
    - "*.pdf"
    - "*.txt"
    - "*.asc"
    sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/docs
