# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Colebaugh dot com
subtitle: Notes on Development, Operations, and Security
email: raymondcolebaugh@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Guides and notes from a software engineer with interests in security, automation, and machine learning.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.colebaugh.com" # the base hostname & protocol for your site
twitter_username: rcolebaugh
facebook_username: rcolebaugh
github_username:  raymondcolebaugh
bitbucket_username:  raymondcolebaugh
linkedin_username: raymondcolebaugh
stackexchange_username: raymondcolebaugh
stackexchange_id: 3759451
bitcoin_address: 1Dn2JSjGt1XGPQRq698JqHzzV1cSEK8HYf
practicing:
    - High Scalability
    - Reverse Engineering
    - Network Forensics

# Build settings
markdown: kramdown
collections:
    projects:
        output: true
tag_page_layout: tag-page
tag_page_dir: tag
gems:
    - jekyll-assets
    - jekyll-paginate
    - algoliasearch-jekyll
paginate: 5
assets:
    assets:
    - "*.js"
    - "*.png"
    - "*.jpg"
    - "*.pdf"
    - "*.txt"
    - "*.asc"
    sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/docs
algolia:
  application_id: 'VTA7XL87VN'
  index_name:     'colebaugh.com'
  excluded_files:
    - index.html
exclude:
  - Rakefile
  - README.md
  - script
  - vendor
